function [predictedNormalBody, measurementJacobian] = ...
    planeNormalMeasurementModel(attitudeRad, referenceNormalGlobal)
%PLANENORMALMEASUREMENTMODEL 预测有向全局法向量在机体系下的表达。
%
%   作者：Wenshao Lyu

    rollRad = attitudeRad(1);
    pitchRad = attitudeRad(2);
    yawRad = attitudeRad(3);

    rotationX = [ ...
        1, 0, 0; ...
        0, cos(rollRad), -sin(rollRad); ...
        0, sin(rollRad), cos(rollRad)];
    rotationY = [ ...
        cos(pitchRad), 0, sin(pitchRad); ...
        0, 1, 0; ...
        -sin(pitchRad), 0, cos(pitchRad)];
    rotationZ = [ ...
        cos(yawRad), -sin(yawRad), 0; ...
        sin(yawRad), cos(yawRad), 0; ...
        0, 0, 1];

    derivativeX = [ ...
        0, 0, 0; ...
        0, -sin(rollRad), -cos(rollRad); ...
        0, cos(rollRad), -sin(rollRad)];
    derivativeY = [ ...
        -sin(pitchRad), 0, cos(pitchRad); ...
        0, 0, 0; ...
        -cos(pitchRad), 0, -sin(pitchRad)];
    derivativeZ = [ ...
        -sin(yawRad), -cos(yawRad), 0; ...
        cos(yawRad), -sin(yawRad), 0; ...
        0, 0, 0];

    % 观测函数为全局参考法向量经旋转矩阵转置后的机体系表达。
    rotationBodyToGlobal = rotationZ * rotationY * rotationX;
    predictedNormalBody = rotationBodyToGlobal.' * referenceNormalGlobal(:);

    % 分别对 roll、pitch、yaw 求导，构造姿态观测 Jacobian。
    derivativeRoll = rotationZ * rotationY * derivativeX;
    derivativePitch = rotationZ * derivativeY * rotationX;
    derivativeYaw = derivativeZ * rotationY * rotationX;
    attitudeJacobian = [ ...
        derivativeRoll.' * referenceNormalGlobal(:), ...
        derivativePitch.' * referenceNormalGlobal(:), ...
        derivativeYaw.' * referenceNormalGlobal(:)];
    measurementJacobian = [attitudeJacobian, zeros(3, 3)];
end
