function program = build_tilted_insertion_program(scene, plan)
%BUILD_TILTED_INSERTION_PROGRAM 将A*运输路径转换为倾斜插入动作程序。
%   该函数只生成TCP pose和waypoint，不连接或驱动机器人硬件。

    parameters = tilted_insertion_motion_config();
    [startPosition, startTheta, slotPosition, slotTheta] = ...
        unpack_scene(scene);
    path = unpack_plan(plan);

    tolerance = parameters.positionToleranceMm;
    if norm(path(1, :) - startPosition) > tolerance ...
            || norm(path(end, :) - slotPosition(1:2)) > tolerance
        error('build_tilted_insertion_program:ScenePlanMismatch', ...
              'plan.path的起终点与小物体和槽入口不一致。');
    end

    travelHeight = parameters.pickHeightMm ...
        + parameters.travelOffsetMm;
    pickRotation = downward_tcp_rotation(startTheta);
    slotRotation = downward_tcp_rotation(slotTheta);
    [tiltedRotation, tiltedRotationMatrix] = ...
        rotate_tcp_about_local_x( ...
            slotRotation, parameters.tiltAngleRad);

    clearanceOffset = tiltedRotationMatrix ...
        * [0; 0; parameters.tiltClearanceOffsetMm];
    insertionOffset = tiltedRotationMatrix ...
        * [0; 0; parameters.insertionDistanceMm];
    retreatOffset = tiltedRotationMatrix ...
        * [0; 0; parameters.retreatDistanceMm];

    program.prePickPose = [startPosition, travelHeight, pickRotation];
    program.pickPose = [ ...
        startPosition, parameters.pickHeightMm, pickRotation];
    program.liftPose = program.prePickPose;
    program.transportWaypoints = build_transport_waypoints( ...
        path, travelHeight, pickRotation, parameters);

    program.preAlignPose = [ ...
        slotPosition(1:2), travelHeight, slotRotation];
    program.tiltClearancePose = program.preAlignPose;
    program.tiltClearancePose(1:3) = ...
        program.preAlignPose(1:3) + clearanceOffset.';
    program.tiltClearancePose(4:6) = tiltedRotation;

    program.slotApproachPose = [ ...
        slotPosition + clearanceOffset.', tiltedRotation];
    program.insertPose = program.slotApproachPose;
    program.insertPose(1:3) = ...
        program.slotApproachPose(1:3) + insertionOffset.';
    program.retreatPose = program.insertPose;
    program.retreatPose(1:3) = ...
        program.insertPose(1:3) + retreatOffset.';
    program.homePose = parameters.homePose;
    program.parameters = parameters;
end

function [startPosition, startTheta, slotPosition, slotTheta] = ...
        unpack_scene(scene)
    requiredFields = {'smallItem', 'slotEntrance'};
    if ~isstruct(scene) || ~isscalar(scene) ...
            || ~all(isfield(scene, requiredFields))
        error('build_tilted_insertion_program:InvalidScene', ...
              'scene缺少倾斜插入动作所需字段。');
    end
    [startPosition, startTheta] = unpack_pose( ...
        scene.smallItem, 2, 'scene.smallItem');
    [slotPosition, slotTheta] = unpack_pose( ...
        scene.slotEntrance, 3, 'scene.slotEntrance');
end

function [position, theta] = unpack_pose(pose, dimension, argumentName)
    if ~isstruct(pose) || ~isscalar(pose) ...
            || ~all(isfield(pose, {'position', 'theta'}))
        error('build_tilted_insertion_program:InvalidScene', ...
              '%s必须包含position和theta。', argumentName);
    end
    position = pose.position;
    theta = pose.theta;
    if ~isnumeric(position) || ~isreal(position) ...
            || ~isequal(size(position), [1, dimension]) ...
            || any(~isfinite(position(:))) ...
            || ~isnumeric(theta) || ~isreal(theta) ...
            || ~isscalar(theta) || ~isfinite(theta)
        error('build_tilted_insertion_program:InvalidScene', ...
              '%s必须提供有效的position和theta。', argumentName);
    end
    position = double(position);
    theta = double(theta);
end

function path = unpack_plan(plan)
    requiredFields = {'method', 'path', 'reachedGoal', ...
        'stopReason', 'insideBoard', 'clearanceSafe'};
    if ~isstruct(plan) || ~isscalar(plan) ...
            || ~all(isfield(plan, requiredFields))
        error('build_tilted_insertion_program:InvalidPlan', ...
              'plan缺少倾斜插入执行所需字段。');
    end
    if ~(ischar(plan.method) ...
            || (isstring(plan.method) && isscalar(plan.method))) ...
            || string(plan.method) ~= "astar"
        error('build_tilted_insertion_program:InvalidPlan', ...
              '倾斜插入动作只接受A*运输计划。');
    end
    path = plan.path;
    if ~isnumeric(path) || ~isreal(path) || ~ismatrix(path) ...
            || isempty(path) || size(path, 2) ~= 2 ...
            || any(~isfinite(path(:)))
        error('build_tilted_insertion_program:InvalidPlan', ...
              'plan.path必须是非空N x 2有限实数矩阵。');
    end
    logicalFields = {'reachedGoal', 'insideBoard', 'clearanceSafe'};
    for fieldIndex = 1:numel(logicalFields)
        value = plan.(logicalFields{fieldIndex});
        if ~islogical(value) || ~isscalar(value)
            error('build_tilted_insertion_program:InvalidPlan', ...
                  '%s必须是逻辑标量。', logicalFields{fieldIndex});
        end
    end
    if ~(ischar(plan.stopReason) ...
            || (isstring(plan.stopReason) ...
                && isscalar(plan.stopReason)))
        error('build_tilted_insertion_program:InvalidPlan', ...
              'plan.stopReason必须是字符向量或字符串标量。');
    end
    if ~plan.reachedGoal || string(plan.stopReason) ~= "goal_reached" ...
            || ~plan.insideBoard || ~plan.clearanceSafe
        error('build_tilted_insertion_program:PlanNotExecutable', ...
              '只有成功且通过工作区和clearance检查的A*路径才能执行。');
    end
    path = double(path);
end

function waypoints = build_transport_waypoints( ...
        path, travelHeight, rotationVector, parameters)
    waypointCount = size(path, 1) - 1;
    if waypointCount == 0
        waypoints = zeros(0, 10);
        return;
    end
    poses = [path(2:end, :), ...
        repmat(travelHeight, waypointCount, 1), ...
        repmat(rotationVector, waypointCount, 1)];
    motion = repmat([parameters.jointAcceleration, ...
        parameters.jointVelocity, parameters.time, ...
        parameters.blendRadiusM], waypointCount, 1);
    motion(end, 4) = 0;
    waypoints = [poses, motion];
end
