function elevatedCorners = project_marker_to_elevated_plane( ...
        basePlaneCorners, cameraBasePosition, planeHeight)
%PROJECT_MARKER_TO_ELEVATED_PLANE 将桌面投影修正到已知高度平面。
%   Homography只能给出相机射线与Z=0桌面的交点basePlaneCorners。
%   已知相机光心C和目标平面Z=h后，同一射线在该平面的XY交点为
%   Cxy + ((Cz-h)/Cz)*(P0xy-Cxy)。该方法假设两个平面平行，不能
%   替代完整相机标定或任意三维位姿重建。

    if ~isnumeric(basePlaneCorners) || ~isreal(basePlaneCorners) ...
            || ~isequal(size(basePlaneCorners), [4, 2]) ...
            || any(~isfinite(basePlaneCorners(:)))
        error('project_marker_to_elevated_plane:InvalidCorners', ...
              'basePlaneCorners必须是4x2有限实数矩阵。');
    end
    if ~isnumeric(cameraBasePosition) || ~isreal(cameraBasePosition) ...
            || numel(cameraBasePosition) ~= 3 ...
            || any(~isfinite(cameraBasePosition(:)))
        error('project_marker_to_elevated_plane:InvalidCameraPosition', ...
              'cameraBasePosition必须包含三个有限实数。');
    end
    if ~isnumeric(planeHeight) || ~isreal(planeHeight) ...
            || ~isscalar(planeHeight) || ~isfinite(planeHeight)
        error('project_marker_to_elevated_plane:InvalidPlaneHeight', ...
              'planeHeight必须是有限实数标量。');
    end

    basePlaneCorners = double(basePlaneCorners);
    cameraBasePosition = reshape(double(cameraBasePosition), 1, 3);
    planeHeight = double(planeHeight);
    if cameraBasePosition(3) <= planeHeight ...
            || abs(cameraBasePosition(3)) <= 1e-12
        error('project_marker_to_elevated_plane:InvalidGeometry', ...
              '相机光心必须位于目标高度平面上方。');
    end

    rayScale = (cameraBasePosition(3) - planeHeight) ...
        / cameraBasePosition(3);
    elevatedXY = cameraBasePosition(1:2) ...
        + rayScale * (basePlaneCorners - cameraBasePosition(1:2));
    elevatedCorners = [elevatedXY, repmat(planeHeight, 4, 1)];
end
