function [rotationVector, rotationMatrix] = ...
        rotate_tcp_about_local_x(currentRotationVector, angle)
%ROTATE_TCP_ABOUT_LOCAL_X 绕当前TCP局部X轴右乘旋转angle。
%   返回UR旋转向量和旋转后的TCP到Base旋转矩阵。

    if ~isnumeric(currentRotationVector) ...
            || ~isreal(currentRotationVector) ...
            || numel(currentRotationVector) ~= 3 ...
            || any(~isfinite(currentRotationVector(:)))
        error('rotate_tcp_about_local_x:InvalidRotationVector', ...
              'currentRotationVector必须包含三个有限实数。');
    end
    if ~isnumeric(angle) || ~isreal(angle) || ~isscalar(angle) ...
            || ~isfinite(angle)
        error('rotate_tcp_about_local_x:InvalidAngle', ...
              'angle必须是有限实数标量。');
    end

    currentRotation = rotvec2mat3d( ...
        reshape(double(currentRotationVector), 1, 3));
    angle = double(angle);
    localXRotation = [ ...
        1,          0,           0; ...
        0, cos(angle), -sin(angle); ...
        0, sin(angle),  cos(angle)];
    rotationMatrix = currentRotation * localXRotation;
    rotationVector = rotmat2vec3d(rotationMatrix);
end
