function rotationBodyToGlobal = eulerZYXRotation(attitudeRad)
%EULERZYXROTATION 构造从机体系到全局坐标系的 ZYX 旋转矩阵。
%
%   作者：Wenshao Lyu

    rollRad = attitudeRad(1);
    pitchRad = attitudeRad(2);
    yawRad = attitudeRad(3);

    rotationX = [ ...
        1, 0, 0; ...
        0, cos(rollRad), -sin(rollRad); ...
        0, sin(rollRad), cos(rollRad)];
    rotationY = [ ...
        cos(pitchRad), 0, sin(pitchRad); ...
        0, 1, 0; ...
        -sin(pitchRad), 0, cos(pitchRad)];
    rotationZ = [ ...
        cos(yawRad), -sin(yawRad), 0; ...
        sin(yawRad), cos(yawRad), 0; ...
        0, 0, 1];

    rotationBodyToGlobal = rotationZ * rotationY * rotationX;
end
